### ISSUE TITLE
Adding Contributing Guidelines

### ISSUE THREAD

**Issue by krupalitrivedi** [heysagnik/screenREC#17]
It is important to have contributing guidelines if your project is up for people to contribute so that you don't have a hassle in the future when people contribute.

**Comment by heysagnik** [comment]
Can you work on this?

**Comment by krupalitrivedi** [comment]
I can work on this! Are you going to open this repo for hacktoberfest, is it okay to make the pull request during hacktoberfest? or do you want me to do it before that? Both work for me :)

**Comment by heysagnik** [comment]
It would be better if you do it now

**Comment by krupalitrivedi** [comment]
alright!
