### ISSUE TITLE
Add Web Cam Recording 

### ISSUE THREAD

**Issue by heysagnik** [heysagnik/screenREC#20]
Users are requesting this feature from long time.

**Comment by Savio629** [comment]
@heysagnik I can add this feature!
So the webcam recording will contain
1.Option to start and stop the recording 
2.Instantly download the video!
Anything else?

**Comment by heysagnik** [comment]
Ok yeah that's it

**Comment by Savio629** [comment]
I am bit lost here! I haven't used pug before.
Also I thought of adding the web camera by refer this website https://usefulangle.com/post/354/javascript-record-video-from-camera
Should I refer some different websites? Can you suggest some?
Also can you give a short idea on which all files need to be change?
My understanding -
- Add WebCAM js component(Also add scss component to it).
- Make changes in index.js file.
- Need to add a partials of webcam.pug ?

**Comment by heysagnik** [comment]
Yeah your understandings are correct
😅 Actually I was also refering from that site

**Comment by Suraj-Bhandarkar-S** [comment]
I will be able to make the changes for this also, if its pending let me know :)

**Comment by heysagnik** [comment]
@Suraj-Bhandarkar-S assigned you, you can work on this issue

**Comment by Suraj-Bhandarkar-S** [comment]
I have created the feature. Please Test :)

**Comment by Savio629** [comment]
I was kinda busy with some other work so couldn't work on this issue.Btw great work @Suraj-Bhandarkar-S 👏

**Comment by Savio629** [comment]
If any help or fix is needed would try to work on it!

**Comment by heysagnik** [comment]
> If any help or fix is needed would try to work on it!

Try implementing new UI in the PR #43

**Comment by Suraj-Bhandarkar-S** [comment]
@Savio629 can you check the feature and if its working in your browser ?
