### ISSUE TITLE
Stop sharing button bug

### ISSUE THREAD

**Issue by yashchaudhari008** [heysagnik/screenREC#21]
**Describe the bug**
App crashes if the user clicks on ``` Stop sharing ``` button.

![image](https://user-images.githubusercontent.com/29065088/192157049-ba9287fb-ebf6-4b4e-a324-3ab6c96b15f5.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Start recording
2. Click on ```Stop sharing``` button of the chrome popup UI.
3. App crashes here!

**Expected behaviour**
Recording should be stopped and video recorded till that time should be saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/29065088/192157010-f005d5ed-6146-4b57-95c9-ac23636e4826.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 105.0.5195.127

**Comment by utkarsh006** [comment]
@yashchaudhari008 I think the issues are in recorder.js file. Can you assign the issue to me?

**Comment by yashchaudhari008** [comment]
Bug is still not fixed fully! It doesn't work when sharing/recording chrome tab and we click stop button.

Refer screenshot :- 
![image](https://user-images.githubusercontent.com/29065088/195086051-b09142d6-e309-42ff-b355-c0559e8538e9.png)

**Comment by heysagnik** [comment]
@BWsix Can you check??

**Comment by BWsix** [comment]
@heysagnik Sure but maybe tomorrow (I mean 24-ish hours later), as I'm currently cramming for tomorrow's midterm exam😅

**Comment by heysagnik** [comment]
Ok ok no issues then

**Comment by Villain45** [comment]
@BWsix What is the bug exactly? I didn't get u

**Comment by BWsix** [comment]
@Villain45 That blue "stop sharing" button on the top of the page should not stay there after user ends the record

**Comment by Villain45** [comment]
@BWsix but on my screen this bug is not there, am I missing something?

**Comment by BWsix** [comment]
@Villain45 It seems like the bug only appears when do tab record

**Comment by BWsix** [comment]
@heysagnik @yashchaudhari008 @Villain45 
Take a look at #42, it's working on my device now.
