### ISSUE TITLE
Add a GitHub Star 🌟 button 

### ISSUE THREAD

**Issue by heysagnik** [heysagnik/screenREC#26]
Add a GitHub Star 🌟 button somewhat like this one: 
[Demo](https://codepen.io/aaroniker/pen/BaZJMjv)

**Comment by AriesTropixDev** [comment]
okay will do :)

**Comment by yadavsairaj** [comment]
Hey can i work on this?

**Comment by heysagnik** [comment]
Yeah you both can start working on it.

**Comment by yadavsairaj** [comment]
hey @heysagnik  i believe styles (css) file is missing

**Comment by heysagnik** [comment]
@yadavsairaj the styling is not done with css 😑, I used Saas styling. 
So what is the need of .css file ? 
Look for .scss file in order to implement styling

**Comment by lucalves** [comment]
@heysagnik in which part of the layout (up, down, right, left) should the button be included?

**Comment by heysagnik** [comment]
Near the dark mode button @lucalves 
Would you love to work on this?

**Comment by lucalves** [comment]
> Near the dark mode button @lucalves Would you love to work on this?

I've been looking at the code, but I have no knowledge about the pug framework :(

**Comment by Anuran12** [comment]
@heysagnik  could you assign this to me ? I made this type of contribution before.. and i guess it will be better if i add stars and forks like this 👇

![IMG_20221006_172113.jpg](https://user-images.githubusercontent.com/104062485/194680419-18f21417-0a37-4c1f-95a7-0295ad0bbb97.jpg)

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/194713676-77cd7348-c8ec-4843-aeec-ffdb0d8da8bb.png)

![image](https://user-images.githubusercontent.com/104062485/194713693-47990fe5-68d6-40da-a155-a13f95addae3.png)


is it okay ? I am unable to toggle  the dark/light mode on the star and fork buttons

**Comment by Anuran12** [comment]
@heysagnik do I have to change the position ? or is it okay there ?

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/194714004-67334d00-5ec4-4121-83cd-d6dd0e37e655.png)
![image](https://user-images.githubusercontent.com/104062485/194714006-91e97381-4b2d-4070-8310-3944f87f3cf8.png)


I guess its better to make the buttons color white. @heysagnik

**Comment by heysagnik** [comment]
Well done 👍
Just fix these 
- Remove the fork button
- And move the star button near the dark mode toogle button

**Comment by Anuran12** [comment]
@heysagnik okay..

**Comment by heysagnik** [comment]
@Anuran12 First Create a PR so that I can add `hacktoberfest-accepted` label

**Comment by Anuran12** [comment]
![image](https://user-images.githubusercontent.com/104062485/194719081-0145fd45-3885-4faa-8e7b-35512d63b0c3.png)
![image](https://user-images.githubusercontent.com/104062485/194719084-73e38e99-5938-4806-a8ca-c65ba57e4c22.png)


okay?

**Comment by Anuran12** [comment]
> @Anuran12 First Create a PR so that I can add `hacktoberfest-accepted` label

It's okay no need to hurry... ;)  Already my 7 PRs are merged. but still I am contributing because I am liking to contribute  ^_^

**Comment by Anuran12** [comment]
@yadavsairaj  hey...

**Comment by Anuran12** [comment]
@heysagnik hey..
