### ISSUE TITLE
Social  Media Icons 

### ISSUE THREAD

**Issue by HridoyHazard** [heysagnik/screenREC#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HridoyHazard** [comment]
assign this task to me. if you think this project need nice social media icons

**Comment by heysagnik** [comment]
Assigned you.
let me see the preview , if I like it then will merge the issue

**Comment by HridoyHazard** [comment]
thank you plz don't assign it to other. i will make it beautiful. give me some time. i will create a pr and show you the preview

**Comment by HridoyHazard** [comment]
![image](https://user-images.githubusercontent.com/71395891/194691201-61c669d0-d67e-4ce1-98b0-6980b81e10eb.png)
i'm getting this error while run the project @heysagnik

**Comment by heysagnik** [comment]
It needs Linux operating system, or run in Gitpod

**Comment by HridoyHazard** [comment]
![image](https://user-images.githubusercontent.com/71395891/194695755-4da14411-40a2-4480-87b7-e5daf54eab37.png)
i've installed the gitpod in my vscode but it still not working....can you plz guide me a little ? since i haven't tried this before

**Comment by heysagnik** [comment]
Click on this link , you it will work 
https://gitpod.io/#https://github.com/heysagnik/screenREC
