### ISSUE TITLE
Save user selected color scheme to localstorage

### ISSUE THREAD

**Issue by BWsix** [heysagnik/screenREC#30]
**Is your feature request related to a problem? Please describe.**

Users have to select color scheme every time they visit the page, if they want to use a different color scheme from browser's default color scheme.

**Describe the solution you'd like**

- After user toggles color scheme, save their decision to localstorage.
  - key : `screenREC-color-scheme`
  - value : "light" | "dark"
- Before querying browser's `prefers-color-scheme` for color scheme, see if there is an existing color scheme in localstorage

**Describe alternatives you've considered**

Sorry, I could not think of any alternatives.

Does this feature request sounds appeal to you? if so, I'm willing to make a PR for this!

**Comment by BWsix** [comment]
By the way, do we have limits on how long a record could be?
This web app is really helpful if I need to record my online classes, which lasts about 50 minutes per session.

**Comment by heysagnik** [comment]
> 

Yeah you are good to go with this issue

**Comment by devocoe** [comment]
can you assign me this issue ?

**Comment by heysagnik** [comment]
> By the way, do we have limits on how long a record could be? This web app is really helpful if I need to record my online classes, which lasts about 50 minutes per session.

Actually the recordings are saved in chunks, in every chunck it stores 200ms video and the chunks are added one by one and it's get converted into the whole recording.

I have tried recording for 15 mins and not more than that, It has potential to record more , have to check it

**Comment by BWsix** [comment]
Hi @devocoe I'm already working on this

**Comment by BWsix** [comment]
> > By the way, do we have limits on how long a record could be? This web app is really helpful if I need to record my online classes, which lasts about 50 minutes per session.
> 
> Actually the recordings are saved in chunks, in every chunck it stores 200ms video and the chunks are added one by one and it's get converted into the whole recording.
> 
> I have tried recording for 15 mins and not more than that, It has potential to record more , have to check it

I see, thank you for the reply!
