### ISSUE TITLE
Detection of user device 

### ISSUE THREAD

**Issue by heysagnik** [heysagnik/screenREC#34]
**Describe the bug**
ScreenREC doesn't support on mobile devices , so when someone visits the site trhoug mobile then the user must be alerted that `"Mobile device not supported"` through a toast or banner.

**Comment by buneeIsSlo** [comment]
Hey! I'm willing to work on this.

**Comment by Anuran12** [comment]
@heysagnik  I can do this .. assign it to me please

**Comment by buneeIsSlo** [comment]
@heysagnik I'm running into an issue upon entering the command `npm run format`. This modifies 11 files on my side with different indentations than the original files. Below is an example:

![formatHelp](https://user-images.githubusercontent.com/79749200/194746869-9702d4fd-e3db-4550-be9b-8cffbcef7471.PNG)

Any clue on what's happening?

**Comment by heysagnik** [comment]
What is the need of `npm run format` here ?

**Comment by buneeIsSlo** [comment]
@heysagnik I agree, but the pre-commit automatically runs it when I try to commit.

**Comment by heysagnik** [comment]
It sounds weird , never happened with me.

**Comment by buneeIsSlo** [comment]
I've tried disabling my prettier extension and auto-formatting, buy nothing seems to work :(

**Comment by buneeIsSlo** [comment]
@heysagnik I managed to create a PR. I had to delete the pre-commit file in order to do this. Please have a look at it.
