### ISSUE TITLE
Wrong download format

### ISSUE THREAD

**Issue by Dun-sin** [heysagnik/screenREC#44]
**Describe the bug**
When set the format for download to `mp4` the downloaded format is `webm`

**To Reproduce**
1. Select `webm`
2. Record your screen
3. download it

**Expected behavior**
should be `mp4` file extension

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by heysagnik** [comment]
I think it's not a bug it's the feature.
