### ISSUE TITLE
Naming the video 

### ISSUE THREAD

**Issue by heysagnik** [heysagnik/screenREC#46]
**Describe the bug**
If some one by mistake input a dot or any punctuation mark as the name then it should ask for a new name, otherwise after the user downloads the video , he won't be able to open the file.

**To Reproduce**
1. Go to the website
2. Name the video to 'hello.html'
3. Record randomly and download it 

**Expected behavior**
It should show a warning message when the users save by invalid names 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : chrome
 - Version : latest

**Comment by heysagnik** [comment]
@Villain45 please can you fix it? After merging a  user reached out to me with this issue.

**Comment by pathakharsh123** [comment]
Sir can I take this issue

**Comment by Villain45** [comment]
@heysagnik Yeah will do
But I guess it will not give any error, the downloaded file is easily opened and can be played since it will again concatenated with the extension
