### ISSUE TITLE
Fix README typos

### ISSUE THREAD

**Issue by guiszk** [heysagnik/screenREC#75]
There are a few typos in the Installation Guide for Windows Users or Local Developement section, including command names.

View errors on `README.md`

"Developement" should be changed to "development".
`px parcel src/index.pug` should be changed to `npx parcel src/index.pug`

I can fix this, if you'd like!

**Comment by Villain45** [comment]
Other than that can u add more things into it and make it look better?

**Comment by guiszk** [comment]
I could add instructions on how to use the live website, like enabling browser popups and such.

**Comment by Villain45** [comment]
Also make a Demo video of using it and place it after installation guide

**Comment by guiszk** [comment]
Sure!
