### ISSUE TITLE
Big preview of screen record with not regular aspect ratio

### ISSUE THREAD

**Issue by aalystama** [heysagnik/screenREC#8]
Getting a big preview when the video's aspect ratio is not regular. I've tried to record an Android emulator.

![Screenshot from 2021-12-26 11-44-05](https://user-images.githubusercontent.com/45136151/147400086-667c6fd9-7b27-498d-97c1-9772a6758803.png)
![Screenshot from 2021-12-26 11-44-15](https://user-images.githubusercontent.com/45136151/147400088-f9c04588-28ac-473b-885e-0f158806eadf.png)

**Comment by devgossips** [comment]
Can you please elaborate the issue ?
@aalystama

**Comment by yashchaudhari008** [comment]
I could reproduce the same issue.
![image](https://user-images.githubusercontent.com/29065088/192157286-6ed0ad72-4a8f-40a8-9d33-b0a61486e479.png)

**Comment by heysagnik** [comment]
Wanna work on this too ?

**Comment by yashchaudhari008** [comment]
Sure
